Correct typo, and add apparmor dep
home-assistant/supervised-installer pull request #172
Opened 2021-11-23 09:18 UTC by cincodenada

It's required by the deb package, so we should probably install it here since dpkg doesn't pull in deps

2021-11-23 09:18 UTC, homeassistant commented
Hi @cincodenada, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#172).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-06-23 08:04 UTC, frenck approved these changes
Thanks, @cincodenada 👍

2022-06-23 08:05 UTC, homeassistant commented
Hi @cincodenada, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#172).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-06-23 08:05 UTC, frenck requested changes
It seems like our CLA isn't signed. Without it, we cannot process or merge this PR. Could you take a look @cincodenada? Thanks! 👍

2022-09-15 09:12 UTC, frenck commented
Closing this PR as stale.

2022-09-15 09:12 UTC, closed without merging